### PR TITLE
Add api dependencies in pom.xml

### LINKED ISSUE #16: Add dependencies in pom.xml
**Problem**

After updating this library to 2.0.1 (from 1.4.0), the app crashes when tapping on the notification / opening the Gander Intent because the `PagedListAdapter` could not be found.
Stacktrace:

```
FATAL EXCEPTION: main
    Process: [my.application.id.redacted], PID: 25551
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/paging/PagedListAdapter;
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        [...]
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.paging.PagedListAdapter" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/my.application.id.redacted-FPnU4r2hjkGlbkGlYtumgg==/base.apk"],nativeLibraryDirectories=[/data/app/my.application.id.redacted-FPnU4r2hjkGlbkGlYtumgg==/lib/arm64, /data/app/my.application.id.redacted-FPnU4r2hjkGlbkGlYtumgg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        [...]
```

The application itself does not use the PagedListAdapter and therefore does not declare a dependency for it.

So the easy solution is to just add the missing dependencies needed by gander (in my case `androidx.paging:paging-runtime` and `androidx.lifecycle:lifecycle-extensions`). 

**Cleaner Solution**

To not force the library users to declare the missing dependencies in their applications, it would be nice to have the required dependencies of this library declared within its [pom.xml](http://central.maven.org/maven2/com/ashokvarma/android/gander/2.0.1/gander-2.0.1.pom).
An example to do so can be found here: https://stackoverflow.com/a/30523571/5045290 (I'm not that familiar with your maven deployment process, though).

I'm happy to provide a PR for that, however, the final implementation / testing would need to be performed by the library owner.

### PR DESCRIPTION
**Pull request by FlowMo7**
This adds all dependencies declared as `api` within the `gander` module to the respective pom.xml.

The pom.xml of the `gander-no-op` module will not be changed by that (and the api-dependency of okhttp (within the `gander-no-op` module) therefore is not added to the pom.xml).
But I guess this is fine, as this library does not make any sense without the library user (the application) itself declaring the okhttp dependency. 

Fixes https://github.com/Ashok-Varma/Gander/issues/16

### CODE REVIEW

**Comment by FlowMo7** [comment]
#16 was changed in another way. Closing this PR.
